### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by MacKarp** [MacKarp/HotScrew#5]
@LK-Herman can you please create application icon? :smile:

**Comment by LK-Herman** [comment]
![LIKE](https://user-images.githubusercontent.com/61921500/143613828-24b48146-406f-494c-97c3-2791f742defd.png)

**Comment by LK-Herman** [comment]
![NO](https://user-images.githubusercontent.com/61921500/143613853-293eabce-aebd-4e51-99f1-eba27b1bc8ff.png)

**Comment by LK-Herman** [comment]
I also have green and red version.
![LIKE2](https://user-images.githubusercontent.com/61921500/143613995-391e987a-cf4b-4c8f-ac32-de4963c54529.png)
![NO2](https://user-images.githubusercontent.com/61921500/143614002-9a215a06-191b-4057-aaa1-05b8767981ef.png)
.

**Comment by LK-Herman** [comment]
..and app icon
![ICON1](https://user-images.githubusercontent.com/61921500/143614206-69cfc63d-ed14-404e-bca3-54057e94e1f3.png)
![ICON2](https://user-images.githubusercontent.com/61921500/143614214-8580f950-1120-42ad-9004-1bcbe7288341.png)

![ICON3](https://user-images.githubusercontent.com/61921500/143614219-eb1b7eef-5e74-40d4-adf0-5a4ce0f7b7b7.png)
![ICON4](https://user-images.githubusercontent.com/61921500/143614225-c07355e3-7a52-4e58-a3fa-f7fa05f9c967.png)

**Comment by MacKarp** [comment]
Thank you 😄
